// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using okc_quality_reporting.Models;
using System;

namespace okc_quality_reporting.Migrations
{
    [DbContext(typeof(okc_quality_reportingContext))]
    [Migration("20171130062133_AddedFieldTarget")]
    partial class AddedFieldTarget
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("okc_quality_reporting.Models.ReportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CogsPercent");

                    b.Property<string>("Month");

                    b.Property<DateTime>("MonthDate");

                    b.Property<decimal>("Target");

                    b.HasKey("Id");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
